---
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pipenv install --deploy --dev
      - run: pipenv run molecule test --all


workflows:
  version: 2
  commit:
    jobs:
      - test
